name: campusride
description: "A modern Flutter college bus tracking application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI and Design
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  glassmorphism: ^3.0.0
  lottie: ^3.0.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.1
  
  # Backend Integration
  supabase_flutter: ^2.3.4
  google_sign_in: ^6.1.6
  
  # Maps and Location
  location: ^5.0.3
  geolocator: ^11.1.0
  geocoding: ^2.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  maplibre_gl: ^0.21.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  logger: ^2.5.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.4
  dio: ^5.4.1
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.0.2
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/map_style.json
    - assets/images/
    - assets/icons/
    - assets/images/bus_icon.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 