name: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPluginname: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin (dummy package)
version: 0.0.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_linux

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLocalNotificationsLinuxPlugin